{-
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
-}

fib :: Integral a => a -> a
fib 0 = 0
fib 1 = 1
fib n = fib' n 2 1 0

fib' :: Integral a => a -> a -> a -> a -> a
fib' n i n1 n2
    | i < n = fib' n (i+1) (n1+n2) n1
    | i == n = n1 + n2

fibUpTo4M = takeWhile (<4000000) $ map fib [1..]

result = sum $ filter even fibUpTo4M